config/routes.rb
Rails.application.routes.draw do
  delete "logout", to: "user_sessions#destroy"

  resources :usuarios
  resources :user_sessions
  resources :transacoes
  resources :categories

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: {message: "É obrigatório informar o nome."}
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/transacao.rb
class Transacao < ApplicationRecord
  belongs_to :category, optional: true

  validates :valor, presence: {message: "É obrigatório informar o valor!"}
  validates :descricao, presence: {message: "É obrigatório informar a descrição!"}
end

app/models/user_session.rb
# Usuário Sessão
class UserSession
  include ActiveModel::Validations
  include ActiveModel::Conversion

  extend ActiveModel::Naming
  extend ActiveModel::Translation

  attr_accessor :email, :senha

  validates_presence_of :email, :senha

  def initialize(session, attributes = {})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate
    user = Usuario.authenticate(@email, @password)
    if user.present?
      store(user)
      true
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def persisted?
    false
  end

  def current_user
    Usuario.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end
end

app/models/usuario.rb
# Usuário
class Usuario < ApplicationRecord
  validates :nome, presence: {message: "É obrigatório informar o nome!"}
  validates :email, presence: {message: "É obrigatório informar o email!"},
                    format: {
                      with: URI::MailTo::EMAIL_REGEXP,
                      message: "Formato de e-mail inválido!"
                    }
  validates :senha, confirmation: {message: "Senhas divergentes!"}, presence: {message: "É obrigatório informar a senha!"}
  validates :senha_confirmation, presence: {message: "É obrigatório confirmar a senha!"}

  def self.authenticate(email, password)
    user = find_by_email(email)
    return false if user.nil?

    user if user.senha == password
  end
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?, :saldo

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    redirect_to new_user_sessions_path unless user_signed_in?
  end

  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end

  def saldo
    Transacao.where(userId: session[:user_id]).sum('valor')
  end
end

app/controllers/categories_controller.rb
# CategoriesController
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(user_id: session[:user_id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name).reverse_merge({user_id: session[:user_id]}))
    if @category.save
      redirect_to '/categories'
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  def show
    @category = Category.where(id: params[:id], user_id: session[:user_id]).first
    redirect_to '/categories' unless @category
  end
end

app/controllers/home_controller.rb
# HomeController
class HomeController < ApplicationController
  def index; end
end

app/controllers/transacoes_controller.rb
# Transações controller
class TransacoesController < ApplicationController
  def new
    @transacao = Transacao.new
    @categories = Category.where(user_id: session[:user_id])
  end

  def create
    @transacao = Transacao.new(transacao_params)
    if @transacao.save
      redirect_to '/transacoes'
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  def index
    redirect_to '/user_sessions/new' unless session[:user_id]
    @categories = Category.where(user_id: session[:user_id])
    @transacoes = Transacao.where(predicados_filtro)
  end

  def show
    @transacao = Transacao.where(id: params[:id], userId: session[:user_id]).first
    redirect_to '/transacoes' unless @transacao
  end

  private

  def transacao_params
    defaults = {userId: session[:user_id]}
    params.require(:transacao).permit(:category_id || nil, :valor, :descricao).reverse_merge(defaults)
  end

  def predicados_filtro
    predicados = {userId: session[:user_id]}
    category_id = params['category_id']
    descricao = params['descricao']

    predicados['category_id'] = category_id if category_id && category_id != ''
    predicados['descricao'] = descricao if descricao && descricao != ''

    predicados
  end
end

app/controllers/user_sessions_controller.rb
# Controlador de Sessão do Usuário
class UserSessionsController < ApplicationController
  def new
    @session = UserSession.new(session)
  end

  def create
    @session = UserSession.new(session, params[:user_session])
    if @session.authenticate
      redirect_to '/'
    else
      redirect_to '/usuarios/new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/user_sessions/new'
  end
end

app/controllers/usuarios_controller.rb
# Usuario controller
class UsuariosController < ApplicationController
  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      redirect_to '/user_sessions/new'
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  private

  def usuario_params
    params.require(:usuario).permit(:nome, :email, :senha, :senha_confirmation)
  end

  def login
    @session = UserSession.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# HomeHelper
module HomeHelper
end

app/helpers/posts_helper.rb
# this is to help us
module PostsHelper
end

app/helpers/transacoes_helper.rb
# Transacoes helper
module TransacoesHelper
end

app/helpers/usuarios_helper.rb
# Usuario helper
module UsuariosHelper
end

app/views/categories/index.html.erb
<h1>Categorias</h1>

<table class="table table-bordered w-auto">
  <thead class="table-secondary">
  <tr>
    <th class="text-center">Código</th>
    <th>Nome</th>
    <th>Detalhes</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td class="text-center" style="min-width: 150px"><%= category.id %></td>
      <td style="min-width: 300px"><%= category.name %></td>
      <td>
          <%= button_to "Detalhes", category_path(id: category.id), method: :get, class: "btn btn-primary" %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Adicionar Categoria', '/categories/new', 'class' => 'btn btn-primary' %>

app/views/categories/new.html.erb
<h2>Adicionar Categoria</h2>

<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "erro") %> impedem que a categoria seja gravado no banco de dados:
    </h2>

    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with scope: :category, url: categories_path, local: true do |form| %>

  <div class="col-md-6 form-group mb-3">
    <%= form.label 'Nome:', 'for' => 'nome', 'class' => 'form-label' %>
    <%= form.text_field :name, 'id' => 'nome', 'class' => 'form-control', 'placeholder' => 'Informe o nome da categoria' %>
  </div>

  <%= form.submit 'Salvar', 'class' => 'btn btn-primary px-4' %>
<% end %>

app/views/categories/show.html.erb
<h1> Detalhes da categoria <%= @category.id %> </h1>

<p> 
  <strong>Nome:</strong>
  <%= @category.name %>
</p>

<%= button_to "Voltar", categories_path, method: :get, class: "btn btn-secondary" %>

app/views/layouts/_saldo.html.erb
Saldo: R$ <%= saldo %>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="/">Início</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Categorias', '/categories', 'class' => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transações', '/transacoes', 'class' => 'nav-link' %>
        </li>
      </ul>
    </div>

    <div class="pe-3">
      <%= render 'layouts/saldo' %>
    </div>

    <%= button_to 'Sair', logout_path, method: :delete,  class: "btn btn-secondary px-4" %>
  </div>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Entrar', '/user_sessions/new', 'class' => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar', '/usuarios/new', 'class' => 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoEsi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
      <% else %>
        <%= render 'layouts/visitor_navbar' %>
      <% end %>
    </header>
    <div class="container pt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transacoes/index.html.erb
<h1>Listar transações</h1>

<div class="card mb-3">
  <div class="card-header">
    <h5 class="mt-2">Filtro</h5>
  </div>
  <div class="card-body">
    <%= form_with method: :get, url: transacoes_path, local: true do |form| %>
      <% if @categories %>
        <div class="row mb-3">
          <div class="form-group col-md-5">
            <%= form.label 'Categoria', 'for' => 'category', 'class' => 'form-label' %>
            <%= form.select(:category_id, @categories.map { |c| [c.name, c.id] }.insert(0, ''), {}, 'id' => 'category', 'class' => 'form-select', 'value' => params[:category_id]) %>
          </div>
        </div>
      <% end %>

      <div class="form-group mb-3">
        <%= form.label 'Descrição', 'for' => 'descricao', 'class' => 'form-label' %>
        <%= form.text_field :descricao, 'id' => 'descricao', 'class' => 'form-control', 'value' => params[:descricao], 'placeholder' => 'Informe a descrição da transação' %>
      </div>

      <%= form.submit 'Buscar', class: "btn btn-primary px-4" %>
    <% end %>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>Categoria</th>
          <th>Descrição</th>
          <th>Valor</th>
          <th>Ação</th>
        </tr>
        </thead>

        <tbody>
        <% @transacoes.each do |transacao| %>
          <tr>
            <td><%= transacao.category&.name %></td>
            <td><%= transacao.descricao %></td>
            <td><%= transacao.valor %></td>
            <td>
              <%= button_to "Detalhes", transaco_path(id: transacao.id), method: :get, class: "btn btn-primary" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= button_to "Nova transação", new_transaco_path, method: :get, class: "my-2 btn btn-success" %>
<%= button_to "Voltar", root_path, method: :get, class: "btn btn-secondary" %>

app/views/transacoes/new.html.erb
<h1 class="mb-3">Nova transação</h1>

<% if @transacao.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@transacao.errors.count, "erro") %> impedem que a transacao seja gravado no banco de dados:</h2>

    <ul>
      <% @transacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with scope: :transacao, url: transacoes_path, local: true do |form| %>
  <% if @categories %>
    <div class="form-group mb-3">
      <%= form.label 'Categoria', 'for' => 'category', 'class' => 'form-label' %>
      <%= form.select(:category_id, @categories.map { |c| [c.name, c.id] }, {}, 'id' => 'category', 'class' => 'form-select') %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label 'Descrição', 'for' => 'descricao', 'class' => 'form-label' %>
    <%= form.text_field :descricao, 'id' => 'descricao', 'class' => 'form-control' %>
  </div>

  <div class="row mb-3">
    <div class="form-group col-auto">
      <%= form.label :valor, 'for' => 'valor', 'class' => 'form-label' %><br>
      <%= form.text_field :valor, 'id' => 'valor', 'class' => 'form-control' %>
    </div>
  </div>

  <%= form.submit 'Salvar', class: "btn btn-success mb-3" %>
<% end %>

<%= button_to "Voltar", transacoes_path, method: :get, class: "btn btn-secondary" %>

app/views/transacoes/show.html.erb
<h1> Detalhes da transação <%= @transacao.id %> </h1>

<p> 
  <strong>Descrição:</strong>
  <%= @transacao.descricao %>
</p>
 
<p>
  <strong>Valor:</strong>
  <%= @transacao.valor %>
</p>

<%= button_to "Voltar", transacoes_path, method: :get, class: "btn btn-secondary" %>

app/views/user_sessions/new.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-6">
    <h2 class="text-center mb-3">Fazer Login</h2>

    <% if @session.errors.has_key? :base %>
      <div id="error_explanation">
        <%= @session.errors[:base].join(', ') %>
      </div>
    <% end %>

    <%= form_for @session do |f| %>
      <div class="form-group mb-3">
        <%= f.label 'E-mail', 'for' => 'email', 'class' => 'form-label' %>
        <%= f.text_field :email, 'id' => 'email', 'class' => 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= f.label 'Senha', 'for' => 'password', 'class' => 'form-label' %>
        <%= f.password_field :password, 'id' => 'password', 'class' => 'form-control' %>
      </div>

      <div class="d-grid gap-2">
        <%= f.submit 'Entrar', 'class' => 'btn btn-primary px-4' %>
      </div>
    <% end %>
  </div>
</div>

app/views/usuarios/new.html.erb
<h1>Novo usuário</h1>

<% if @usuario.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@usuario.errors.count, "erro") %> impedem que o usuario seja gravado no banco de dados:</h2>
 
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with scope: :usuario, url: usuarios_path, local: true do |form| %>
  <p>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :senha %><br>
    <%= form.text_field :senha, type:"password" %>
  </p>

  <p>
    <%= form.label :"confirmar senha" %><br>
    <%= form.text_field :"senha_confirmation", id:"Confirmar senha", type:"password" %>
  </p>

  <p>
    <%= form.submit 'Salvar' %>
  </p>
<% end %>